package:
  name: cgal
  version: 6.0.1
  epoch: 0
  description: Efficient and reliable geometric algorithms as C++ library
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 50cfbde3b84dbeae8338268db2d78fe4fcb522de
      repository: https://github.com/CGAL/cgal
      tag: v${{package.version}}

  - uses: cmake/configure

  - uses: cmake/build

  - uses: cmake/install

  - runs: |
      mkdir -p ${{targets.contextdir}}/usr/bin/
      cp Scripts/scripts/cgal_create_CMakeLists ${{targets.contextdir}}/usr/bin/cgal_create_CMakeLists
      cp Scripts/scripts/cgal_create_cmake_script ${{targets.contextdir}}/usr/bin/cgal_create_cmake_script

  - uses: strip

subpackages:
  - name: cgal-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - cgal
    description: cgal dev
    test:
      pipeline:
        - uses: test/pkgconf
        - uses: test/tw/ldd-check

  - name: cgal-doc
    pipeline:
      - uses: split/manpages
    description: cgal manpages
    test:
      pipeline:
        - uses: test/docs

update:
  enabled: true
  git:
    strip-prefix: v
