package:
  name: containers-storage
  version: "1.59.1"
  epoch: 0
  description: "Storage configuration for container tools"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/containers/storage
      tag: v${{package.version}}
      expected-commit: fe5d8be24c0735a1b27f6e8727471cf2a5ba9c9a

  - runs: |
      # Set default storage driver to overlay
      sed -E 's/(driver =) ""/\1 "overlay"/' -i storage.conf

      # Create necessary directories
      mkdir -p "${{targets.destdir}}/etc/containers"
      mkdir -p "${{targets.destdir}}/usr/share/containers"

      # Install storage configuration
      install -m 644 storage.conf "${{targets.destdir}}/etc/containers/storage.conf"
      install -m 644 storage.conf "${{targets.destdir}}/usr/share/containers/storage.conf"

# Note: This package should be updated in coordination with containers-common
# to maintain version synchronization across the container ecosystem
update:
  enabled: false
  manual: true
  exclude-reason: Package updates are coordinated with containers-common to maintain ecosystem synchronization

test:
  pipeline:
    - name: Verify storage configuration
      runs: |-
        stat /etc/containers/storage.conf
        stat /usr/share/containers/storage.conf
        grep -q 'driver = "overlay"' /etc/containers/storage.conf
        echo "containers-storage configuration verified"
